/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICumulativeMerkleDrop128, ICumulativeMerkleDrop128Interface } from "../../interfaces/ICumulativeMerkleDrop128.js";

  const _abi = [
  {
    "inputs": [],
    "name": "InvalidProof",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MerkleRootWasUpdated",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NothingToClaim",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "Claimed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "bytes16",
        "name": "oldMerkleRoot",
        "type": "bytes16"
      },
      {
        "indexed": false,
        "internalType": "bytes16",
        "name": "newMerkleRoot",
        "type": "bytes16"
      }
    ],
    "name": "MerkelRootUpdated",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes16",
        "name": "salt",
        "type": "bytes16"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "cumulativeAmount",
        "type": "uint256"
      },
      {
        "internalType": "bytes16",
        "name": "expectedMerkleRoot",
        "type": "bytes16"
      },
      {
        "internalType": "bytes",
        "name": "merkleProof",
        "type": "bytes"
      }
    ],
    "name": "claim",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "merkleRoot",
    "outputs": [
      {
        "internalType": "bytes16",
        "name": "",
        "type": "bytes16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes16",
        "name": "merkleRoot_",
        "type": "bytes16"
      }
    ],
    "name": "setMerkleRoot",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "token",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ICumulativeMerkleDrop128__factory {
    static readonly abi = _abi;
    static createInterface(): ICumulativeMerkleDrop128Interface {
      return new Interface(_abi) as ICumulativeMerkleDrop128Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): ICumulativeMerkleDrop128 {
      return new Contract(address, _abi, runner) as unknown as ICumulativeMerkleDrop128;
    }
  }
  