/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'CumulativeMerkleDrop', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CumulativeMerkleDrop__factory>
getContractFactory(name: 'CumulativeMerkleDrop128', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CumulativeMerkleDrop128__factory>
getContractFactory(name: 'SignatureMerkleDrop128', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SignatureMerkleDrop128__factory>
getContractFactory(name: 'TokenMock', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TokenMock__factory>
getContractFactory(name: 'ICumulativeMerkleDrop', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ICumulativeMerkleDrop__factory>
getContractFactory(name: 'ICumulativeMerkleDrop128', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ICumulativeMerkleDrop128__factory>
getContractFactory(name: 'ISignatureMerkleDrop128', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISignatureMerkleDrop128__factory>

  getContractAt(name: 'CumulativeMerkleDrop', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CumulativeMerkleDrop>
getContractAt(name: 'CumulativeMerkleDrop128', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CumulativeMerkleDrop128>
getContractAt(name: 'SignatureMerkleDrop128', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SignatureMerkleDrop128>
getContractAt(name: 'TokenMock', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TokenMock>
getContractAt(name: 'ICumulativeMerkleDrop', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ICumulativeMerkleDrop>
getContractAt(name: 'ICumulativeMerkleDrop128', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ICumulativeMerkleDrop128>
getContractAt(name: 'ISignatureMerkleDrop128', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISignatureMerkleDrop128>

  deployContract(name: 'CumulativeMerkleDrop', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CumulativeMerkleDrop>
deployContract(name: 'CumulativeMerkleDrop128', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CumulativeMerkleDrop128>
deployContract(name: 'SignatureMerkleDrop128', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SignatureMerkleDrop128>
deployContract(name: 'TokenMock', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenMock>
deployContract(name: 'ICumulativeMerkleDrop', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICumulativeMerkleDrop>
deployContract(name: 'ICumulativeMerkleDrop128', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICumulativeMerkleDrop128>
deployContract(name: 'ISignatureMerkleDrop128', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISignatureMerkleDrop128>

  deployContract(name: 'CumulativeMerkleDrop', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CumulativeMerkleDrop>
deployContract(name: 'CumulativeMerkleDrop128', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CumulativeMerkleDrop128>
deployContract(name: 'SignatureMerkleDrop128', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SignatureMerkleDrop128>
deployContract(name: 'TokenMock', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenMock>
deployContract(name: 'ICumulativeMerkleDrop', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICumulativeMerkleDrop>
deployContract(name: 'ICumulativeMerkleDrop128', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICumulativeMerkleDrop128>
deployContract(name: 'ISignatureMerkleDrop128', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISignatureMerkleDrop128>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  