/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SignatureMerkleDrop128Interface extends Interface {
    getFunction(nameOrSignature: "claim" | "depth" | "isClaimed" | "merkleRoot" | "owner" | "renounceOwnership" | "rescueFunds" | "token" | "transferOwnership" | "verify(bytes,bytes16,bytes16)" | "verify(bytes,bytes16)"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'claim', values: [AddressLike, BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'depth', values?: undefined): string;
encodeFunctionData(functionFragment: 'isClaimed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'merkleRoot', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rescueFunds', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verify(bytes,bytes16,bytes16)', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'verify(bytes,bytes16)', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depth', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'merkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rescueFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify(bytes,bytes16,bytes16)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify(bytes,bytes16)', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SignatureMerkleDrop128 extends BaseContract {
    
    connect(runner?: ContractRunner | null): SignatureMerkleDrop128;
    waitForDeployment(): Promise<this>;

    interface: SignatureMerkleDrop128Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    claim: TypedContractMethod<
      [receiver: AddressLike, amount: BigNumberish, merkleProof: BytesLike, signature: BytesLike, ],
      [void],
      'payable'
    >
    

    
    depth: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isClaimed: TypedContractMethod<
      [index: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    merkleRoot: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rescueFunds: TypedContractMethod<
      [token_: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    "verify(bytes,bytes16,bytes16)": TypedContractMethod<
      [proof: BytesLike, root: BytesLike, leaf: BytesLike, ],
      [[boolean, bigint] & {valid: boolean, index: bigint }],
      'view'
    >
    

    
    "verify(bytes,bytes16)": TypedContractMethod<
      [proof: BytesLike, leaf: BytesLike, ],
      [[boolean, bigint] & {valid: boolean, index: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [receiver: AddressLike, amount: BigNumberish, merkleProof: BytesLike, signature: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'depth'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isClaimed'): TypedContractMethod<
      [index: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'merkleRoot'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rescueFunds'): TypedContractMethod<
      [token_: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verify(bytes,bytes16,bytes16)'): TypedContractMethod<
      [proof: BytesLike, root: BytesLike, leaf: BytesLike, ],
      [[boolean, bigint] & {valid: boolean, index: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'verify(bytes,bytes16)'): TypedContractMethod<
      [proof: BytesLike, leaf: BytesLike, ],
      [[boolean, bigint] & {valid: boolean, index: bigint }],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }