/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ICumulativeMerkleDrop128Interface extends Interface {
    getFunction(nameOrSignature: "claim" | "merkleRoot" | "setMerkleRoot" | "token"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Claimed" | "MerkelRootUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'claim', values: [BytesLike, AddressLike, BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'merkleRoot', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMerkleRoot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'merkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMerkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
  }

  
    export namespace ClaimedEvent {
      export type InputTuple = [account: AddressLike, amount: BigNumberish];
      export type OutputTuple = [account: string, amount: bigint];
      export interface OutputObject {account: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MerkelRootUpdatedEvent {
      export type InputTuple = [oldMerkleRoot: BytesLike, newMerkleRoot: BytesLike];
      export type OutputTuple = [oldMerkleRoot: string, newMerkleRoot: string];
      export interface OutputObject {oldMerkleRoot: string, newMerkleRoot: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ICumulativeMerkleDrop128 extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICumulativeMerkleDrop128;
    waitForDeployment(): Promise<this>;

    interface: ICumulativeMerkleDrop128Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    claim: TypedContractMethod<
      [salt: BytesLike, account: AddressLike, cumulativeAmount: BigNumberish, expectedMerkleRoot: BytesLike, merkleProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    merkleRoot: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setMerkleRoot: TypedContractMethod<
      [merkleRoot_: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [salt: BytesLike, account: AddressLike, cumulativeAmount: BigNumberish, expectedMerkleRoot: BytesLike, merkleProof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'merkleRoot'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setMerkleRoot'): TypedContractMethod<
      [merkleRoot_: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Claimed'): TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
getEvent(key: 'MerkelRootUpdated'): TypedContractEvent<MerkelRootUpdatedEvent.InputTuple, MerkelRootUpdatedEvent.OutputTuple, MerkelRootUpdatedEvent.OutputObject>;

    filters: {
      
      'Claimed(address,uint256)': TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
      Claimed: TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
    

      'MerkelRootUpdated(bytes16,bytes16)': TypedContractEvent<MerkelRootUpdatedEvent.InputTuple, MerkelRootUpdatedEvent.OutputTuple, MerkelRootUpdatedEvent.OutputObject>;
      MerkelRootUpdated: TypedContractEvent<MerkelRootUpdatedEvent.InputTuple, MerkelRootUpdatedEvent.OutputTuple, MerkelRootUpdatedEvent.OutputObject>;
    
    };
  }