/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ISignatureMerkleDrop128Interface extends Interface {
    getFunction(nameOrSignature: "claim" | "depth" | "isClaimed" | "merkleRoot" | "token" | "verify"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'claim', values: [AddressLike, BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'depth', values?: undefined): string;
encodeFunctionData(functionFragment: 'isClaimed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'merkleRoot', values?: undefined): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'verify', values: [BytesLike, BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depth', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'merkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
  }

  

  export interface ISignatureMerkleDrop128 extends BaseContract {
    
    connect(runner?: ContractRunner | null): ISignatureMerkleDrop128;
    waitForDeployment(): Promise<this>;

    interface: ISignatureMerkleDrop128Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    claim: TypedContractMethod<
      [receiver: AddressLike, amount: BigNumberish, merkleProof: BytesLike, signature: BytesLike, ],
      [void],
      'payable'
    >
    

    
    depth: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isClaimed: TypedContractMethod<
      [index: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    merkleRoot: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verify: TypedContractMethod<
      [proof: BytesLike, root: BytesLike, leaf: BytesLike, ],
      [[boolean, bigint] & {valid: boolean, index: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [receiver: AddressLike, amount: BigNumberish, merkleProof: BytesLike, signature: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'depth'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isClaimed'): TypedContractMethod<
      [index: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'merkleRoot'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verify'): TypedContractMethod<
      [proof: BytesLike, root: BytesLike, leaf: BytesLike, ],
      [[boolean, bigint] & {valid: boolean, index: bigint }],
      'view'
    >;

    

    filters: {
      
    };
  }